### ISSUE TITLE
Unable Share in Platform Android and IOS 

### ISSUE THREAD

**Issue by diigel** [ChainTechNetwork/ComposeMultiplatformScreenCapture#1]
Compose Multiplatform Android and IOS 

###  Android 

Missing FLAG_ACTIVITY_NEW_TASK 

<img width="1366" alt="Screenshot 2024-05-15 at 13 47 09" src="https://github.com/ChainTechNetwork/ComposeMultiplatformScreenCapture/assets/55740024/080ef1b9-0ef7-468b-ab61-f484aee71c24">

### IOS  ( Use Simulator IOS iPhone 13 mini )

<img width="1587" alt="Screenshot 2024-05-15 at 13 53 03" src="https://github.com/ChainTechNetwork/ComposeMultiplatformScreenCapture/assets/55740024/6b9225b4-b26c-4c3e-9051-d1120ed92e7e">

**Comment by ctn-mobile-innovation** [comment]
@diigel Thanks for reporting, Let us check and get back to you

**Comment by LaatonWalaBhoot** [comment]
@ctn-mobile-innovation Any update on this?

**Comment by kalist28** [comment]
@ctn-mobile-innovation Are you going to fix it?

**Comment by ctn-mobile-innovation** [comment]
Sorry for late reply, we will be pushing new update in few hours, Please check it and by chance still you face same issue let us know!

**Comment by ctn-mobile-innovation** [comment]
@kalist28 @LaatonWalaBhoot @diigel Can you please confirm if it's fixed in new update, so we can close this issue

**Comment by alfayedoficial** [comment]
still issue 
android.util.AndroidRuntimeException: Calling startActivity() from outside of an Activity context requires the FLAG_ACTIVITY_NEW_TASK flag. Is this really what you want?
	at android.app.ContextImpl.startActivity(ContextImpl.java:1127)
	at android.app.ContextImpl.startActivity(ContextImpl.java:1103)
	at android.content.ContextWrapper.startActivity(ContextWrapper.java:436)
	at network.chaintech.composeMultiplatformScreenCapture.utility.UtilityKt$share$2.invokeSuspend(utility.kt:47)
	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
	at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:101)
	at android.os.Handler.handleCallback(Handler.java:958)
